name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'v0.10.0'
    - name: Build wasm-pack
      run: wasm-pack build
      working-directory: ./kr-engne
    - name: Install node packages
      run: npm install
      working-directory: ./kr-engne/www
    - name: Install node packages
      run: npm install
      working-directory: ./kr-engne/www
    - name: Build dist
      run: npm run build
      working-directory: ./kr-engne/www
      if: ${{ github.ref == 'refs/heads/master' }}
